(function(){
  const main=document.querySelector('main');
  function renderAbout(){
    main.innerHTML=`<section class="manifesto-hero"><span class="eyebrow">About Curio</span><h1>Make something<br><em>of what you notice.</em></h1><p>Curio is a weekly collection of ideas for people who are curious about how the world can be made, remade, and felt differently.</p></section><section class="manifesto-body"><div class="manifesto-lead"><span class="eyebrow">A small manifesto</span><h2>We believe an idea is not finished when it is understood.</h2><p>It is finished when it gives someone a way to begin.</p></div><div class="manifesto-principles"><article><span>01</span><h3>Look closer.</h3><p>The most useful ideas often start with a small observation: a scent, a habit, a room, a place, a sound. We collect work that makes the overlooked easier to notice.</p></article><article><span>02</span><h3>Move between fields.</h3><p>Fashion can borrow from space technology. A map can hold friendship. A family story can become a book. We are interested in the paths between disciplines.</p></article><article><span>03</span><h3>Keep the language clear.</h3><p>Wonder does not need vagueness. Every idea here tells you what it is, who made it, and why it might matter.</p></article><article><span>04</span><h3>Make room for the small.</h3><p>Not every project needs to become a platform. A useful object, a beautiful experiment, or a new way to gather people can be enough.</p></article><article><span>05</span><h3>Pass it on.</h3><p>Curio is meant to be shared. Take an idea, send it to someone, adapt it, or make a version that belongs to you.</p></article><article><span>06</span><h3>Stay unfinished.</h3><p>This is a living collection. The point is not to close the question, but to keep finding better ones.</p></article></div></section><section class="manifesto-invite"><span class="eyebrow">Bring us something</span><h2>What are you noticing?</h2><p>We are looking for small companies, artists, tools, places, and experiments that help people experience the world in a new way.</p><p class="submission-note">Submissions will open soon.</p></section>`;
    document.title='Curio — About';
    document.querySelectorAll('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route==='about'));
    window.scrollTo(0,0);
  }
  function maybe(){if(location.hash==='#about')renderAbout();}
  window.addEventListener('hashchange',maybe); maybe();
})();
