/* Editorial seed collection. Original sources last checked September 18, 2026.
   Observations and prompts are Commonwealth's editorial interpretations. */
const IDEAS = [
{id:'coperni',name:'Coperni',title:'A bag made from 99% air',category:'Design',theme:'Materials',icon:'bag',color:'yellow',maker:'Coperni & Ioannis Michaloudis',year:'2024',description:'The Air Swipe Bag is made from silica aerogel, an exceptionally light material. The 33-gram design turns a familiar accessory into an experiment with how little matter an object needs.',why:'A material used in space technology finds an unexpected role in fashion. It is a useful example of ideas moving between disciplines.',prompt:'What material from another field could change something you are making?',url:'https://www.istitutomarangoni.com/en/maze35/design/the-coperni-can-revolution-whats-behind-the-99-air-swipe-bag',source:'Istituto Marangoni'},
{id:'corner',name:'Corner',title:'Places recommended by friends',category:'Apps',theme:'Connection',icon:'map',color:'blue',maker:'Eliza Wu & Jake Xia',year:'Ongoing',description:'A social map for saving and discovering places through personal taste and recommendations. It helps turn scattered suggestions into places you can actually find again.',why:'A map can reflect the people you trust and the experiences you enjoy, as well as geography.',prompt:'What would you include in a guide to your neighborhood for one particular friend?',url:'https://www.corner.inc/guides',source:'Corner'},
{id:'remento',name:'Remento',title:'Family stories in a book',category:'Apps',theme:'Memory',icon:'book',color:'pink',maker:'Charlie Greene & Alex Massonneau',year:'Founded 2021',description:'Family members answer prompts by speaking. Remento turns recordings into written stories and a printed book, with QR codes that link back to the original voice.',why:'It makes a large, emotional task—preserving family stories—possible through a series of small conversations.',prompt:'Which question would help you learn something new about someone close to you?',url:'https://www.remento.co/how-it-works',source:'Remento'},
{id:'osmo',name:'Osmo',title:'Capture and recreate scents',category:'Technology',theme:'Senses',icon:'scent',color:'green',maker:'Osmo',year:'Demonstrated 2024',description:'Osmo describes a laboratory process that analyzes a scent, translates it into data, and sends a recipe to a formulation robot to recreate it. An early experiment used a slice of coconut.',why:'A sensory quality of a physical object can be recorded and recreated elsewhere. The company calls this process scent teleportation.',prompt:'Which smell would you want to preserve from a place you love?',url:'https://www.osmo.ai/blog/update-scent-teleportation-we-did-it',source:'Osmo'},
{id:'blur',name:'Blur Building',title:'A building made of fog',category:'Design',theme:'Senses',icon:'cloud',color:'blue',maker:'Diller Scofidio + Renfro',year:'2002 · historical',description:'For the Swiss Expo in Yverdon-les-Bains, a pavilion was enveloped in fog produced from lake water. The temporary structure was later dismantled.',why:'Architecture becomes an atmosphere you move through, changing the way you notice space and your own senses.',prompt:'Could you define a space using light, sound, or temperature?',url:'https://dsrny.com/project/blur-building',source:'Diller Scofidio + Renfro'},
{id:'labyrinth',name:'Invisible Labyrinth',title:'A maze without physical walls',category:'Art',theme:'Senses',icon:'maze',color:'pink',maker:'Jeppe Hein',year:'2005 · historical',description:'Visitors wore headsets that vibrated when they encountered infrared boundaries. The maze organized their movements without visible walls. It was first exhibited at the Centre Pompidou in Paris.',why:'A structure can exist through feedback and perception. The boundaries are experienced rather than built.',prompt:'How could a simple signal guide people through an experience?',url:'https://www.jeppehein.net/project_id.php?id=125&path=works',source:'Jeppe Hein'},
{id:'cities',name:'Cities and Memory',title:'Hear a place, then its reinterpretation',category:'Sound',theme:'Memory',icon:'wave',color:'green',maker:'Cities and Memory contributors',year:'Ongoing',description:'A collaborative sound project pairs field recordings of real places with artistic reinterpretations, allowing listeners to compare the original sound with a new composition.',why:'The same place can become many different experiences through another person’s attention and imagination.',prompt:'Record a minute of your surroundings. What changes when you listen with your eyes closed?',url:'https://citiesandmemory.com/what-is-cities-and-memory-about/',source:'Cities and Memory'},
{id:'winderen',name:'Jana Winderen',title:'Listen inside a frozen landscape',category:'Sound',theme:'Senses',icon:'wave',color:'blue',maker:'Jana Winderen',year:'Energy Field · 2010',description:'Energy Field layers recordings from glacier crevasses, fjords, and the open ocean, captured on trips to Greenland, Norway, and the Barents Sea.',why:'Sound offers a way to encounter environments and animal activity that ordinary photographs cannot convey.',prompt:'What could listening reveal about somewhere you think you already know?',url:'https://www.janawinderen.com/releases/energy-field',source:'Jana Winderen'},
{id:'ruefle',name:'Mary Ruefle',title:'New poems from erased pages',category:'Art',theme:'Expression',icon:'book',color:'pink',maker:'Mary Ruefle',year:'Ongoing practice',description:'Ruefle covers words in old books with correction fluid, paint, and collage. The remaining fragments form new poems. A selection appeared in The Paris Review in 2025.',why:'Removing material can create new meaning. Editing becomes a visible creative act.',prompt:'What happens if you keep only ten words from a page?',url:'https://www.theparisreview.org/blog/2025/08/12/erasure-notebooks/',source:'The Paris Review'},
{id:'holosonics',name:'Audio Spotlight',title:'Sound you can step into',category:'Technology',theme:'Senses',icon:'wave',color:'yellow',maker:'Holosonics',year:'Established technology',description:'Directional speakers use ultrasound to create focused listening areas. Audio can be directed toward a particular part of a room.',why:'Sound can create a boundary or a private moment without a physical partition.',prompt:'Where would a small, focused listening area be useful?',url:'https://www.holosonics.com/',source:'Holosonics'},
{id:'ghost',name:'A Ghost Story',title:'A film about home, time, and attachment',category:'Film',theme:'Memory',icon:'house',color:'blue',maker:'David Lowery',year:'2017',description:'A ghost returns to the house he shared with his partner. The film explores love, grief, and the passing of time through a place and its changing inhabitants.',why:'It offers an emotional reference for thinking about the attachments that remain when people and surroundings change.',prompt:'Which detail makes a place feel like home to you?',url:'https://a24films.com/films/a-ghost-story',source:'A24'},
{id:'cosmos',name:'Cosmos',title:'A place for your visual inspiration',category:'Apps',theme:'Expression',icon:'collage',color:'pink',maker:'Andy McCune & Luca Marra',year:'Ongoing',description:'Collect images, videos, links, and notes into visual collections. Explore related references and search by color or visual similarity.',why:'Things you collect can reveal connections in your taste before you have the words to describe them.',prompt:'Collect five images from different fields that seem to belong together.',url:'https://www.cosmos.so/',source:'Cosmos'},
{id:'whering',name:'Whering',title:'New outfits from clothes you own',category:'Apps',theme:'Expression',icon:'shirt',color:'yellow',maker:'Bianca Rangecroft & the Whering team',year:'Ongoing',description:'Digitize your clothes, plan outfits, receive styling suggestions, and explore friends’ wardrobes. The app helps you see more possibilities in the things you own.',why:'Software can help people get more value and enjoyment from existing possessions.',prompt:'What could you combine differently instead of buying something new?',url:'https://whering.co.uk/',source:'Whering'},
{id:'airbuds',name:'Airbuds',title:'Keep up through the music you play',category:'Apps',theme:'Connection',icon:'wave',color:'green',maker:'Airbuds',year:'Ongoing',description:'A widget lets friends share their listening activity and react to one another’s music.',why:'An everyday habit becomes a lightweight way of feeling connected, even without a conversation.',prompt:'What song would tell a friend something about your day?',url:'https://apps.apple.com/us/app/airbuds-widget/id1638906106',source:'App Store'},
{id:'soundmap',name:'Soundmap',title:'Collect music as you explore',category:'Apps',theme:'Connection',icon:'map',color:'blue',maker:'Soundmap',year:'First version 2024',description:'Walk around to collect songs at map locations, trade with other fans, and build in-game collections. Collecting a song does not give ownership of music rights.',why:'The rituals of collecting and exchanging music become a digital game connected to physical movement.',prompt:'What familiar hobby could encourage people to explore their surroundings?',url:'https://apps.apple.com/gb/app/soundmap-music-collecting/id6476420863',source:'App Store'},
{id:'timeleft',name:'Timeleft',title:'Meet new people over dinner',category:'Apps',theme:'Connection',icon:'table',color:'pink',maker:'Timeleft',year:'Ongoing',description:'The service matches people for gatherings and handles venues and logistics. Its dinner format brings a person together with five new faces.',why:'Technology can arrange the conditions for a relationship to begin in the physical world.',prompt:'What small gathering would help people in your community feel welcome?',url:'https://timeleft.com/',source:'Timeleft'},
{id:'polycam',name:'Polycam',title:'Turn a room into a 3D capture',category:'Technology',theme:'Memory',icon:'house',color:'green',maker:'Polycam',year:'Ongoing',description:'Tools for capturing objects and spaces as digital 3D models, floor plans, and virtual walkthroughs.',why:'A physical space becomes something you can explore and share remotely. It preserves spatial relationships as well as appearances.',prompt:'Which space would you want to capture before it changes?',url:'https://poly.cam/',source:'Polycam'},
{id:'mymind',name:'mymind',title:'Find the things you meant to remember',category:'Apps',theme:'Memory',icon:'collage',color:'yellow',maker:'mymind',year:'Ongoing',description:'A private place for notes, bookmarks, images, and articles, with associative search using details such as color, keywords, or brands.',why:'An archive can work with partial recollections and associations rather than require a perfect filing system.',prompt:'How would you describe something you remember visually but cannot name?',url:'https://mymind.com/',source:'mymind'},
{id:'mantel',name:'Mantel',title:'Bring scattered memories together',category:'Apps',theme:'Memory',icon:'collage',color:'pink',maker:'Isabella Serrano Martinez & Aekta Shah van Dijk',year:'Emerging platform',description:'Mantel describes a memory platform that combines personal media such as photos, locations, and calendars, using AI to compose moments for reflection and sharing.',why:'The story of a day can live across several formats. Bringing them together can make it easier to revisit.',prompt:'Which three different traces would tell the story of yesterday?',url:'https://www.mantelmoments.com/the-platform',source:'Mantel'}
];
const PLACES = [
{id:'blur',name:'Yverdon-les-Bains',country:'Switzerland',label:'Former pavilion · 2002',note:'The site of the Swiss Expo Blur Building, on Lake Neuchâtel. The pavilion was temporary and has been dismantled.',x:57,y:53,lat:46.78,lon:6.64},
{id:'labyrinth',name:'Paris',country:'France',label:'Past exhibition · 2005',note:'Centre Pompidou hosted the first exhibition of Jeppe Hein’s Invisible Labyrinth. This pin documents that exhibition, not a current installation.',x:47,y:43,lat:48.86,lon:2.35},
{id:'winderen',name:'Greenland',country:'Recording region',label:'Field recordings · released 2010',note:'One of the regions recorded for Energy Field. The pin is regional, not an exact recording site or a visitor destination.',x:18,y:17,lat:72,lon:-40}
];
