'use strict';
const report=window.PROOF_DATA;
const el=id=>document.getElementById(id);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=s=>{try{const u=new URL(s);return ['http:','https:'].includes(u.protocol)?esc(u.href):'#';}catch{return '#';}};
let notes={},storageOK=true;
try{notes=JSON.parse(localStorage.getItem('commonwealth-proof-notes')||'{}');if(!notes||typeof notes!=='object'||Array.isArray(notes))notes={};}catch{storageOK=false;}
function render(){
 const query=el('search').value.toLowerCase(),kind=el('kind').value;
 const items=report.records.filter(r=>(!kind||r.kind===kind)&&JSON.stringify(r).toLowerCase().includes(query));
 el('status').textContent=`${items.length} records shown · report ${report.generatedAt.slice(0,10)} · ${storageOK?'Notes saved in this browser':'Browser storage unavailable: download notes before leaving'}`;
 el('records').innerHTML=items.map(r=>`<article><span class="badge">${esc(r.kind)} · ${r.blockers.length?'Review required':'Cleared at this version'}</span><h2>${esc(r.name)}</h2><div class="columns"><section><h3>Exact copy to proofread</h3>${r.kind==='Website template'?`<details><summary>View full template, including site-wide copy</summary><pre>${esc(r.copy.content)}</pre></details>`:`<dl>${Object.entries(r.copy).filter(([k])=>!['decisions','sources','icon','color','x','y'].includes(k)).map(([k,v])=>`<dt>${esc(k)} ${r.interpretive.includes(k)?'— Commonwealth interpretation':''}</dt><dd>${esc(typeof v==='object'?JSON.stringify(v):v)}</dd>`).join('')}</dl>`}</section><section><h3>Sources and accuracy checks</h3>${r.urls.map(url=>{const l=report.links[url];return `<p><a href="${safeUrl(url)}" target="_blank" rel="noopener noreferrer">${esc(url)}</a><br><small>${esc(l?.state||'Not checked')} ${l?.status||''} · ${esc(l?.checkedAt?.slice(0,10)||'')} ${l?.changed?'· Source changed; compare again':''}</small>${l?.redirected?`<br><small>Redirects to ${esc(l.finalUrl)}</small>`:''}</p>`;}).join('')}<details><summary>${r.blockers.length} checks still needed</summary><ul class="issues">${r.blockers.map(b=>`<li>${esc(b)}</li>`).join('')}</ul></details><h4>Source-to-copy evidence</h4>${r.review?.fields?Object.entries(r.review.fields).map(([field,e])=>`<p><strong>${esc(field)}</strong>: ${esc(e.note)}<br>${(e.sources||[]).map(u=>`<a href="${safeUrl(u)}" target="_blank" rel="noopener noreferrer">Source ↗</a>`).join(' · ')}<br><small>${esc(e.verdict)} · ${esc(e.checkedAt)}</small></p>`).join(''):'<p>No completed comparison yet. Source links and earlier discovery notes do not count as verification.</p>'}<label>Your edits or questions<textarea data-id="${esc(r.id)}" placeholder="For example: this is a prototype, so don’t imply it’s on sale.">${esc(notes[r.id]?.text||'')}</textarea></label>${notes[r.id]&&notes[r.id].hash!==r.hash?'<p class="issues">Your note refers to an older copy version. Please review again.</p>':''}<p><small>Tell Codex to apply your edits. Approval is recorded only after the source checks pass and you approve the final wording.</small></p></section></div></article>`).join('')||'<p>No matching records.</p>';
}
el('records').addEventListener('input',e=>{const id=e.target.dataset.id;if(!id)return;notes[id]={text:e.target.value,hash:report.records.find(r=>r.id===id).hash,updatedAt:new Date().toISOString()};try{localStorage.setItem('commonwealth-proof-notes',JSON.stringify(notes));}catch{storageOK=false;el('status').textContent='Storage unavailable: download your notes before leaving.';}});
el('search').addEventListener('input',render);el('kind').addEventListener('change',render);
el('export').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),notes},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='commonwealth-proofreading-notes.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
render();
